### ISSUE TITLE
pinMode INPUT_PULLUP not implemented

### ISSUE THREAD

**Issue by awenisko** [digistump/DigistumpArduino#10]
In tiny core there's no implementation for pin input mode with pull-up enabled like it is in standard core. I don't see any reason for this to be not implemented and I had proposed the patches for this in pull requests. Is there any reason to not implement this or can you please merge? Thanks.

**Comment by imrehorvath** [comment]
+1

**Comment by riban-bw** [comment]
I agree this should be implemented. The ATtiny85 supports pull-up for each GPIO. I cannot see a PR for this fix.

**Comment by digistump** [comment]
This is implemented in todays coming release
