### ISSUE TITLE
Issue with IDE 1.6.6

### ISSUE THREAD

**Issue by efi** [digistump/DigistumpArduino#13]
In 1.6.6 the DigisparkMouse and DigisparkJoystick examples fail with

> _[...]_\hardware\tools\avr\avr\include\avr\sleep.h:634:6: error: #error "No SLEEP mode defined for this device."

A problem like this is discussed (and solved?) elsewhere: https://github.com/SpenceKonde/ATTinyCore/issues/31

So it's something about
``` C
#if defined(__AVR_ATtiny84__)
```
but a simple `#define __AVR_ATtiny84__` in the sketch did not do the trick for me.

Can someone please look into that issue?

**Comment by efi** [comment]
Well, well, well. With a bit more knowledge about the chip on my Digispark, this would have occured to me earlier:
``` C
#define __AVR_ATtiny85__
```
as the first line in the sketch is sufficient to make the compile error go away and make the device function as HID compatible mouse.

"ATtiny84" was of course wrong and while it allowed a SLEEP mode to be found, some other functions were not executed as intended.

So to solve this issue for everyone, the exampled for DigiMouse and DigiJoystick have to be alterd with the above line before the `#include`s.

**Comment by hodavame** [comment]
Thank you!!!
I also had that problem with the joystick library.

**Comment by digistump** [comment]
I've added this define to the variant pins file for the board so that it doesn't need to be defined anywhere else - releasing today

**Comment by efi** [comment]
Great, thanks!
