### ISSUE TITLE
How to install this package manually?

### ISSUE THREAD

**Issue by LiHangBing** [digistump/DigistumpArduino#131]
Hi~ everyone. Because my network is not OK, always  I install the package by manager  failed.
So how can I download these files and then install the package offline?
Thanks!

**Comment by ArminJo** [comment]
Look at your C:\Users\<YourName>\AppData\Local\Arduino\packages directory to see how other packages are installed.
Download [this repo](https://github.com/ArminJo/DigistumpArduino) and extract the digistump-avr-1.7.0.zip to C:\Users\<YourName>\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.0.
Then xtract the tools\micronucleus-2.0a4-win.zip to 
C:\Users\<YourName>\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4.
Thats it.
Please give me feedback, if this works for you.

**Comment by LiHangBing** [comment]
> Look at your C:\Users<YourName>\AppData\Local\Arduino\packages directory to see how other packages are installed.
> Download [this repo](https://github.com/ArminJo/DigistumpArduino) and extract the digistump-avr-1.7.0.zip to C:\Users<YourName>\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.0.
> Then xtract the tools\micronucleus-2.0a4-win.zip to
> C:\Users<YourName>\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4.
> Thats it.
> Please give me feedback, if this works for you.

OK，it works
But I need copy the file "package_digistump_index.json“ to AppData\Local\Arduino15\
thanks!
