### ISSUE TITLE
HID Keyboard library Implementation is incorrect

### ISSUE THREAD

**Issue by RickeyWard** [digistump/DigistumpArduino#14]
The "DigisparkKeyboard" library is based off of somewhat working but incorrect example code from somewhere out on the internet.

1)
The USBRQ_HID_GET_REPORT request in usbFunctionSetup() should set usbMsgPtr to the report buffer and return the size of the report buffer, returning 0 (which is what the code does now) returns no report when the host asks for one.

There are 2 schools of thought here, either make an empty report buffer, so if the host requests a report when the interrupt buffer is empty we tell it make sure you're not doing anything, or 2 send the last report (which is more risky without support code so hey don't do it)

2)
The sendKeyStroke method is stalling with poll loops (and large delays) waiting for the previous interrupt to be cleared by the host, and to make sure that you don't get repeat keys it does this twice per call, attempting to send an empty report. This breaks all kinds of things when your code becomes complex, and it only works if you don't try to do too much to fast. In fact, its a straight code copy and paste from an example online where the poster says "this works but its not that simple and you shouldn't do it this way"

The proper way to handle it is to store states, and in the update() check if the interrupt is ready, if it is check the state, if the state says to send something send it, then go to a clear state. Then again in update if the interrupt is ready, and you're in clear state, you send that empty report and go into a waiting state.

when you send a key, you just set the report, then set the state to sending, and call update.

This fixes adding meaningless delays to your code that affect everything. Its possible to loose key strokes only if you don't call update() frequently enough, but since the usb specification says it should be called at least every 50ms that shouldn't be a problem anyway.

3)
If the HID descriptor logical maximum was bumped up beyond 101, say to 255. There are other keyboard keys that would work, keys with codes above 101 like keyboard copy/paste ect.

I wrote a library that I'll get along to posting eventually, that is a consumer control device, that allows the digispark to be a very responsive volume knob, but it took a lot of research to find that most of the code in the existing keyboard library is copied from another example that took a lot of liberties. It does work, as long as you aren't doing much of anything else. But as soon as your code gets complicated, it breaks down.

**Comment by digistump** [comment]
A "more proper" Keyboard library would be most welcome, please feel free to submit a pull request with yours!
