### ISSUE TITLE
How to get the latest libraries to Arduino?

### ISSUE THREAD

**Issue by Nurgak** [digistump/DigistumpArduino#19]
I'm having a [issue with VirtualWire](http://digistump.com/board/index.php/topic,1840.0.html) that [has been solved in the latest master branch](https://github.com/digistump/DigistumpArduino/commit/60edebc52bfa425cbc0c549f18fb4bf588735f79), but there's no way to use it with the [standard procedure](http://digistump.com/wiki/digispark/tutorials/connecting) as it only refers to the old 1.6.5 release. How can one download the latest libraries without having to copy the Github files?

**Comment by digistump** [comment]
You can install via board manager and then download these files and copy them over, or you can wait for the next release.

A new release will be out today.
