### ISSUE TITLE
Incorrect #if check

### ISSUE THREAD

**Issue by matthijskooijman** [digistump/DigistumpArduino#27]
This library contains the following line in at least two places:

     #if defined(__AVR_ATtiny85__) || (__AVR_ATtiny2313__) || (__AVR_ATtiny167__)

I believe this is missing `defined` on the second and third part. It probably works because either undefined variables resolve as 0 / false, or perhaps because this library is only used on attiny devices in practice.

**Comment by digistump** [comment]
fixed thanks to a pull request - will be fixed in todays release
