### ISSUE TITLE
Mac OS Board does not show up

### ISSUE THREAD

**Issue by alexellis** [digistump/DigistumpArduino#32]
OS: El Capitain.

Plug in device now... (will timeout in 60 seconds)
> Please plug in the device ... 
> Press CTRL+C to terminate the program.
> Device search timed out

16.5Mhz picked from devices menu after installing board support through Arduino IDE 1.6.8.

Please advise.

**Comment by digistump** [comment]
Please see the forums at digistump.com/board and the wiki at digistump.com/wiki for lots of troubleshooting for OSX

Also note that if it is a clone Digispark from ebay/aliexpress/etc we likely cannot help.

Thanks
