### ISSUE TITLE
OS X 1.5.8c verification error on launch

### ISSUE THREAD

**Issue by davelnewton** [digistump/DigistumpArduino#4]
> "Arduino IDE - Digistump Release 1.5.8C.app" is damaged and can't be opened. You should move it to the trash.

System: Mac Air OS X 1.9.5 8G

1.5.8B has same problem. Is this no longer the IDE to use with the Digisparks?

Let me know what other info is required.

**Comment by davelnewton** [comment]
May be the stub issue; closing until verified.

**Comment by dgdosen** [comment]
I get the same issue...

**Comment by digistump** [comment]
This generally means you need to go enable unverified applications (see the
getting started guide on the wiki) or the extractor you used didn't like
the zip file. Works on 10.9 and 10.10 for me.

**Comment by lukemc** [comment]
Unzipping the DigistumpIDE1.5.8COSX and running the .app gives me:

`Arduino IDE - Digistump Release 1.5.8C.app" is damaged and can't be opened. You should move it to the trash`

Mid 2014, 13"MBPr OSX 10.10.1 (14B25)

**Comment by davelnewton** [comment]
The "unverified applications" thing worked for me, FWIW.
