### ISSUE TITLE
Arduino IDE 1.8.0: esptool2 installed to wrong location

### ISSUE THREAD

**Issue by malaire** [digistump/DigistumpArduino#47]
With Arduino IDE 1.8.0 compiling does not work because esptool2 is installed to

    .../packages/digistump/tools/esptool2/0.9.1/0.9.1/esptool2

instead of

    .../packages/digistump/tools/esptool2/0.9.1/esptool2

**Comment by pfeerick** [comment]
Is this against the right repo @malaire ? This one is for the SAM (DigiX) and AVR (Digispark/Digispark Pro), not the Oak. This think this is an Oak issue, as is documented [here](https://github.com/digistump/OakCore/issues/72). If so, maybe close the issue since it doesn't apply? ;-)

**Comment by malaire** [comment]
yes, I didn't notice that you had several repos for Arduino support. Closing now.
