### ISSUE TITLE
DigiKeyboard Example not working

### ISSUE THREAD

**Issue by IchSkill** [digistump/DigistumpArduino#49]
Im trying to get the Example to work 

Here is the Output after "checking" it 

Arduino: 1.8.0 (Windows 10), Board: "Arduino/Genuino Uno"

In file included from C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:13:0,

                 from C:\Users\IchSkill\Documents\Arduino\sketch_jan05a\sketch_jan05a.ino:1:

c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\delay.h:36:2: warning: #warning "This file has been moved to <util/delay.h>." [-Wcpp]

 #warning "This file has been moved to <util/delay.h>."

  ^

In file included from C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:16:0,

                 from C:\Users\IchSkill\Documents\Arduino\sketch_jan05a\sketch_jan05a.ino:1:

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:479:26: error: variable 'usbDescriptorDevice' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 char usbDescriptorDevice[];

                          ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:485:33: error: variable 'usbDescriptorConfiguration' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 char usbDescriptorConfiguration[];

                                 ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:491:29: error: variable 'usbDescriptorHidReport' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 char usbDescriptorHidReport[];

                             ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:497:27: error: variable 'usbDescriptorString0' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 char usbDescriptorString0[];

                           ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:503:31: error: variable 'usbDescriptorStringVendor' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 int usbDescriptorStringVendor[];

                               ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:509:31: error: variable 'usbDescriptorStringDevice' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 int usbDescriptorStringDevice[];

                               ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/usbdrv.h:515:37: error: variable 'usbDescriptorStringSerialNumber' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 int usbDescriptorStringSerialNumber[];

                                     ^

In file included from C:\Users\IchSkill\Documents\Arduino\sketch_jan05a\sketch_jan05a.ino:1:0:

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:40:73: error: variable 'usbDescriptorHidReport' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 PROGMEM char usbHidReportDescriptor[USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH] = { /* USB report descriptor */

                                                                         ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '161' from 'int' to 'char' inside { } [-Wnarrowing]

 };

 ^

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '224' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '231' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '149' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '129' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '149' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '129' from 'int' to 'char' inside { } [-Wnarrowing]

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:59:1: warning: narrowing conversion of '192' from 'int' to 'char' inside { } [-Wnarrowing]

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,

                 from sketch\sketch_jan05a.ino.cpp:1:

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/scancode-ascii-table.h:6:48: error: redefinition of 'const unsigned char ascii_to_scan_code_table []'

 const unsigned char ascii_to_scan_code_table[] PROGMEM = {

                                                ^

In file included from C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/DigiKeyboard.h:17:0,

                 from C:\Users\IchSkill\Documents\Arduino\sketch_jan05a\sketch_jan05a.ino:1:

C:\Users\IchSkill\Documents\Arduino\libraries\DigisparkKeyboard/scancode-ascii-table.h:6:21: note: 'const unsigned char ascii_to_scan_code_table [119]' previously defined here

 const unsigned char ascii_to_scan_code_table[] PROGMEM = {

                     ^

exit status 1

**Comment by JoelBrun** [comment]
Are you sure you have the right board selected in the "tools"-tab?
