### ISSUE TITLE
Switch AVR TinyWireM lib to adafruit's version

### ISSUE THREAD

**Issue by nfriedly** [digistump/DigistumpArduino#6]
https://github.com/adafruit/TinyWireM

Adafruit's version fleshes out the API a bit to add a couple of missing features and also create aliases of the `send()` & `recieve()` methods to match the Wire library's method `write()` & `read()` names.

This, in turn, grants easier compatibility with a number of other adafruit libraries.

I believe it's fully backwards compatible, although I've only done light testing (with the LCD module).

I can send a PR if you want, but I have to get clearance from my boss first, so it might take a day or two.

**Comment by digistump** [comment]
Thanks - this is done in the newest release coming out now
